azs:
- name: z1
  cloud_properties:
    zone: us-central1-c

vm_types:
- name: small
  cloud_properties:
    machine_type: g1-small
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
- name: small-preemptible
  cloud_properties:
    machine_type: n1-standard-1
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    preemptible: true
- name: medium-preemptible
  cloud_properties:
    machine_type: n1-standard-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    preemptible: true
- name: large-preemptible
  cloud_properties:
    machine_type: n1-standard-4
    root_disk_size_gb: 60
    root_disk_type: pd-ssd
    preemptible: true
- name: compilation
  cloud_properties:
    machine_type: n1-highmem-2
    root_disk_size_gb: 20
    root_disk_type: pd-ssd
    preemptible: true

disk_types:
- name: small
  disk_size: 3000
- name: medium
  disk_size: 25000
- name: large
  disk_size: 50_000

networks:
- name: vip
  type: vip
- name: private
  type: manual
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    static: [10.0.0.3-10.0.0.7]
    cloud_properties:
      network_name: bosh
      subnetwork_name: bosh-us-central1
      xpn_host_project_id: bosh-177015
      ephemeral_external_ip: false
      tags:
        - internal
        - no-ip

compilation:
  workers: 3
  reuse_compilation_vms: true
  az: z1
  vm_type: compilation
  network: private
